site_name: OpenMPF
theme: readthedocs
copyright: OpenMPF

markdown_extensions:
- toc

pages:
- Home: index.md
- Build Guide: Build-Environment-Setup-Guide.md
- Install Guide: Installation.md
- User Guide: User-Guide.md
- Admin Guide: Admin-Manual.md
- Component Documentation:
    - Component Overview: API-Overview.md
    - C++ Component API: CPP-Component-API.md
    - Java Component API: Java-Component-API.md
    - Packaging and Registering a Component: Packaging-and-Registering-a-Component.md
- REST API: REST-API.md
