site_name: OpenMPF
theme: readthedocs
copyright: OpenMPF

markdown_extensions:
- toc

extra_javascript: [js/mustache.js]

use_directory_urls: false

pages:
- Home: index.md
- General:
    - Release Notes: Release-Notes.md
    - License and Distribution: License-And-Distribution.md
    - Acknowledgements: Acknowledgements.md
- Guides:
    - Install Guide: Install-Guide.md
    - Admin Guide: Admin-Guide.md
    - User Guide: User-Guide.md
    - Media Segmentation Guide: Media-Segmentation-Guide.md
    - Feed Forward Guide: Feed-Forward-Guide.md
    - Derivative Media Guide: Derivative-Media-Guide.md
    - Object Storage Guide: Object-Storage-Guide.md
    - Markup Guide: Markup-Guide.md
    - TiesDb Guide: TiesDb-Guide.md
    - REST API: REST-API.md
- Component Development:
    - Component API Overview: Component-API-Overview.md
    - Component Descriptor Reference: Component-Descriptor-Reference.md
    - C++ Batch Component API: CPP-Batch-Component-API.md
    - Python Batch Component API: Python-Batch-Component-API.md
    - Java Batch Component API: Java-Batch-Component-API.md
    - GPU Support Guide: GPU-Support-Guide.md
- Additional Developer Resources:
    - Contributor Guide: Contributor-Guide.md
    - Development Environment Guide: Development-Environment-Guide.md
    - Node Guide: Node-Guide.md
    - Workflow Manager Architecture: Workflow-Manager-Architecture.md
    - C++ Streaming Component API: CPP-Streaming-Component-API.md
